// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendLog(arg1:string):Promise<void>;

export function ClearLog():Promise<void>;

export function GetLog():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ListLuaScripts():Promise<Array<main.ScriptInfo>>;

export function RunLuaScript(arg1:string):Promise<string>;

export function StartScript(arg1:string):Promise<string>;

export function StopScript(arg1:string):Promise<string>;

export function WatchScriptsDir():Promise<void>;
