// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendLog(arg1) {
  return window['go']['main']['App']['AppendLog'](arg1);
}

export function ClearLog() {
  return window['go']['main']['App']['ClearLog']();
}

export function GetLog() {
  return window['go']['main']['App']['GetLog']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListLuaScripts() {
  return window['go']['main']['App']['ListLuaScripts']();
}

export function RunLuaScript(arg1) {
  return window['go']['main']['App']['RunLuaScript'](arg1);
}

export function StartScript(arg1) {
  return window['go']['main']['App']['StartScript'](arg1);
}

export function StopScript(arg1) {
  return window['go']['main']['App']['StopScript'](arg1);
}

export function WatchScriptsDir() {
  return window['go']['main']['App']['WatchScriptsDir']();
}
